### PR TITLE
Added project butter concepts

### PR DESCRIPTION
**Pull request by dimitrieh**
Hi, I saw a post on
[twitter](https://twitter.com/butterproject/status/715157010287865857)
with the some of the concepts of the new butter project icon derived
from Pocholin. I think these improve a bit upon those. Use them if you
like, I think Pocholin is adorable. Credits are nice!

Reference is a butter roll as hairpiece

### CODE REVIEW

**Comment by xaiki** [comment]
haha I like it ! we will need many butters anyway ! some guy wanted a curly butter, maybe we can get there with curly butter rolls ?(i'll let @btzr-io merge this as he's our chief artist right now)

**Comment by xaiki** [comment]
haha I like it ! we will need many butters anyway ! some guy wanted a curly butter, maybe we can get there with curly butter rolls ?

(i'll let @btzr-io merge this as he's our chief artist right now)

**Comment by btzr-io** [comment]
@strages: Hey, we really like what you did, so if you like to join us, 
We just need an email to add you to our slack group: https://butterproject.slack
btw I'm 17, so not much experience, we really  need your help =)

**Comment by dimitrieh** [comment]
Hi bltzr, thanks for the offer :+1: sent you an email

**Comment by btzr-io** [comment]
@strages: Hi, we already sent you an invitation, 
so if you haven't received the email  yet :sweat_smile: , please let me know

**Pull request merged**
